export const defaultValues = {
	url: '',
	stack: '',
	title_check: [],
	console_check: [],
	title_1: '',
	title_2: '',
	title_3: '',
	steps_1: '',
	steps_2: '',
	steps_3: '',
	allure_report: [],
	attachments: [],
	source_code: '',
	ci: '',
	browser_type: '',
	browsers_hub: '',
	notification: [],
	test_management: [],
}
